spring.datasource.url=jdbc:h2:mem:polizasdb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

#IPC como constante en el programa
poliza.ipc=0.0510